name: namekoexample
channels:
- conda-forge
dependencies:
- python=3.7
- pip==20.0.2
- pip:
    - nameko==v3.0.0-rc6
    - marshmallow==2.19.2
    - psycopg2-binary==2.8.2
    - nameko-sqlalchemy==1.5.0
    - alembic==1.0.10
    - pylint==2.5.2
    - debugpy==1.0.0b9
    - bzt==1.14.2
    - pytest==4.5.0
    - coverage==4.5.3
    - flake8==3.7.7
    - redis==3.2.1