name: nameko-devex
channels:
- conda-forge
dependencies:
- openjdk=8.0
- python=3.7
- pip==21
- pip:
    - nameko==v3.0.0-rc9
    - fastapi==0.70.0
    - uvicorn==0.15.0
    - marshmallow==2.19.2
    - psycopg2-binary==2.8.2
    - nameko-sqlalchemy==1.5.0
    - alembic==1.0.10
    - pylint==2.5.2
    - debugpy==1.0.0b9
    - bzt==1.15.3
    - pytest==4.5.0
    - coverage==4.5.3
    - flake8==3.7.7
    - redis==3.2.1